version: "3"
services:
  node:
    container_name: vue
    image: vue
    tty: true
    entrypoint: ["npm", "run", "serve"]
    working_dir: "/var/www/"
    ports: 
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./:/var/www
